//
//  LoginSceneModels.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 KAV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Clean Swift Models передаваемые между
/// IInteractor, Presenter и ViewController
enum LoginSceneModels {
	struct Request {
		var login: String
		var password: String
	}

	struct Responce {
		var success: Bool
		var login: String
		var lastLoginDate: Date
	}

	struct ViewModel {
		var success: Bool
		var userName: String
		var lastLoginDate: String
	}
}
