//
//  LoginSceneViewController.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 KAV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ILoginSceneViewController: AnyObject{
	func render(viewModel: LoginSceneModels.ViewModel)
}

class LoginSceneViewController: UIViewController
{

	private var interactor: ILoginSceneInteractor?
	var router: (NSObjectProtocol & ILoginSceneRouter & LoginSceneDataPassing)?

	var textFieldLogin: UITextField = UITextField()
	var textFieldPass: UITextField = UITextField()

	// MARK: Object lifecycle
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
	{
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}

	required init?(coder aDecoder: NSCoder)
	{
		super.init(coder: aDecoder)
		setup()
	}

	// MARK: Setup
	private func setup()
	{
		let viewController = self
		let worker = LoginWorker()
		let presenter = LoginScenePresenter(viewController: viewController)
		let interactor = LoginSceneInteractor(worker: worker, presenter: presenter)
		let router = LoginSceneRouter(viewController: viewController)
		
		viewController.router = router


		router.viewController = viewController
		//router.dataStore = interactor
	}

	// MARK: Routing
	override func prepare(for segue: UIStoryboardSegue, sender: Any?)
	{
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}

	// MARK: View lifecycle
	override func viewDidLoad()
	{
		super.viewDidLoad()
	}

	@objc func buttonLogin(_ sender: Any) {
		if let email = textFieldLogin.text, let password = textFieldPass.text {
			let request = LoginSceneModels.Request(login: email, password: password)
			interactor?.login(request: request)
		}
	}
}

extension LoginSceneViewController: ILoginSceneViewController {
	func render(viewModel: LoginSceneModels.ViewModel) {
		let alert: UIAlertController

		if viewModel.success {
			alert = UIAlertController(
				title: "Success",
				message: viewModel.userName,
				preferredStyle: UIAlertController.Style.alert
			)
		} else {
			alert = UIAlertController(
				title: "Error",
				message: "",
				preferredStyle: UIAlertController.Style.alert
			)
		}

		let action = UIAlertAction(title: "Ok", style: .default)
		alert.addAction(action)
		present(alert, animated: true, completion: nil)
	}
}
