//
//  LoginScenePresenter.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 KAV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Интерфейс LoginScenePresenter.
protocol ILoginScenePresenter {
	func present(responce: LoginSceneModels.Responce)
}

class LoginScenePresenter: ILoginScenePresenter {
	private weak var viewController: ILoginSceneViewController?

	init(viewController: ILoginSceneViewController?) {
		self.viewController = viewController
	}

	func present(responce: LoginSceneModels.Responce) {
		let viewModel = LoginSceneModels.ViewModel(
			success: responce.success,
			userName: responce.login,
			lastLoginDate: "\(responce.lastLoginDate)"
		)
		viewController?.render(viewModel: viewModel)
	}
}
