//
//  LoginSceneInteractor.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 KAV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ILoginSceneDataStore{
	var email: String? { get set }
	var password: String? { get set }
	var success: Bool? { get set }
	var login: String? { get set }
	var lastLoginDate: Date? { get set }
}

protocol ILoginSceneInteractor {
	func login(request: LoginSceneModels.Request)
}

class LoginSceneInteractor: ILoginSceneInteractor, ILoginSceneDataStore {
	var email: String?
	var password: String?
	var success: Bool?
	var login: String?
	var lastLoginDate: Date?

	private var worker: ILoginWorker
	private var presenter: ILoginScenePresenter?

	init(worker: ILoginWorker, presenter: ILoginScenePresenter?) {
		self.worker = worker
		self.presenter = presenter
	}


	func login(request: LoginSceneModels.Request) {
		let result = worker.login(login: request.login, password: request.password)

		let responce = LoginSceneModels.Responce(
			success: result.success,
			login: result.login,
			lastLoginDate: result.lastLoginDate
		)

		presenter?.present(responce: responce)
	}
}
