//
//  LoginScenePresenter.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScenePresentationLogic
{
  func presentSomething(response: LoginScene.Something.Response)
}

class LoginScenePresenter: LoginScenePresentationLogic
{
  weak var viewController: LoginSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LoginScene.Something.Response)
  {
    let viewModel = LoginScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
