//
//  LoginSceneRouter.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 KAV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ILoginSceneRouter
{
	func routeToMainScene()
}

protocol LoginSceneDataPassing
{
	var dataStore: ILoginSceneDataStore? { get }
}

class LoginSceneRouter: NSObject, ILoginSceneRouter, LoginSceneDataPassing
{
	weak var viewController: LoginSceneViewController?
	var dataStore: ILoginSceneDataStore? = nil

	init(viewController: LoginSceneViewController?) {
		self.viewController = viewController
	}

	func routeToMainScene()
	{
		let destinationVC = assemblyMainScreen
		var destinationDS = destinationVC.router!.dataStore!
		passDataToSomewhere(source: dataStore!, destination: &destinationDS)
		navigateToSomewhere(source: viewController, destination: destinationVC)
	}

	// MARK: Navigation
	func navigateToSomewhere(source: LoginSceneViewController, destination: MainSceneViewController)
	{
	  source.show(destination, sender: nil)
	}

	// MARK: Passing data
	func passDataToSomewhere(source: LoginSceneDataStore, destination: inout SomewhereDataStore)
	{
	  destination.name = source.name
	}

	private func assemblyMainScreen() -> MainSceneViewController {
		let viewController = MainSceneViewController()
		let taskManager = OrderedTaskManager(taskManager: TaskManager())
		let repository: ITaskRepository = TaskRepositoryStub()
		taskManager.addTasks(tasks: repository.getTasks())
		let sections = SectionForTaskManagerAdapter(taskManager: taskManager)

		let presenter = MainScenePresenter(view: viewController, sectionManager: sections)
		viewController.presenter = presenter

		return viewController
	}
}
