//
//  LoginSceneRouter.swift
//  TodoList
//
//  Created by Коломенский Александр on 23.02.2023.
//  Copyright (c) 2023 KAV. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ILoginSceneRouter
{
	
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginSceneDataPassing
{
  var dataStore: ILoginSceneDataStore? { get }
}

class LoginSceneRouter: NSObject, ILoginSceneRouter, LoginSceneDataPassing
{
  weak var viewController: LoginSceneViewController?
  var dataStore: ILoginSceneDataStore? = nil

	init(viewController: LoginSceneViewController?) {
		self.viewController = viewController
	}
  // MARK: Routing
  
//  func routeToSomewhere(viewController: UIStoryboardSegue?)
//  {
//    if let segue = segue {
//      let destinationVC = segue.destination as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//      let storyboard = UIStoryboard(name: "Main", bundle: nil)
//      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//      navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//  }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: LoginSceneViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: LoginSceneDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
